#!/usr/bin/env python3
"""Generate `.citation-links.json`: where every paper label is defined.

The map a VS Code extension needs to make this project's citations clickable.  Every
docstring citation names a `\\label`; this says which `.tex` file holds that label and on
which line, so `tools/vscode-citations` can turn `` (`def:recovery-timing`, lines
87-222) `` into a link that opens the paper there.

**`tools/check_citations.py` owns the citation grammar and the label-to-paper
resolution**, and this file imports both rather than restating them: `SPECS` and
`HFT_TEX` for which sources hold which labels, `environment_spans` for the result
environments whose line span the checker already computes.  What is added here is the one
thing the checker has no use for: where a label is *defined*, for every label, not only
for the lemma-like environments.

Output is written to the repository root and is **gitignored**.  It is derived from the
submodule, it names files by repository-relative path, and it is regenerated by
`make citation-links`.  A machine-specific absolute path never appears in it: the
extension prefixes the workspace root at load time, the way `mapping.html` does for its
own jump links.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from check_citations import ROOT, SPECS, HFT_TEX, environment_spans

OUT = ROOT.joinpath(".citation-links.json")

# A label *definition* in the paper, which is none of the checker's citation forms: those
# match a citation in our files, this matches the `\label` a citation points at.
LABEL_DEF = re.compile(r"\\label\{([^}]+)\}")


def labels_in(tex: Path, prefix: str = "") -> dict[str, dict[str, object]]:
    """Every label defined in one `.tex`, with the line it sits on.

    `prefix` is the checker's own device for telling the two papers apart: a label of the
    companion paper is cited as `hft:def:store`, so it is recorded under that key."""
    out: dict[str, dict[str, object]] = {}
    for lineno, line in enumerate(tex.read_text().splitlines(), 1):
        for label in LABEL_DEF.findall(line):
            key = prefix + label
            if key not in out:
                out[key] = {"file": tex.relative_to(ROOT).as_posix(), "line": lineno}
    return out


def main() -> int:
    labels: dict[str, dict[str, object]] = {}
    clashes: list[str] = []

    sources = [(tex, "") for tex in sorted(SPECS.glob("*.tex"))]
    if HFT_TEX.exists():
        sources.append((HFT_TEX, "hft:"))

    for tex, prefix in sources:
        for key, where in labels_in(tex, prefix).items():
            if key in labels:
                clashes.append(f"{key}: {labels[key]['file']} and {where['file']}")
            else:
                labels[key] = where

    # The line span, for the results the checker already spans.  A citation of one of
    # those points at the environment's first line either way; carrying the span lets the
    # extension show it, and a reader check it, without reopening the paper.
    spans = environment_spans(sorted(SPECS.glob("*.tex")))
    if HFT_TEX.exists():
        spans |= environment_spans([HFT_TEX], "hft:")
    for key, (_tex, first, last) in spans.items():
        if key in labels:
            labels[key]["span"] = [first, last]

    for clash in clashes:
        print(f"WARNING duplicate label {clash}", file=sys.stderr)

    OUT.write_text(json.dumps({"labels": labels}, indent=1, sort_keys=True) + "\n")
    spanned = sum(1 for v in labels.values() if "span" in v)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(labels)} labels, {spanned} with spans)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
